### ISSUE TITLE
Correct URI scheme 

### ISSUE THREAD

**Issue by duller999** [dokku/dokku-mongo#1]
Can you please use the standard URI Scheme for MONGO_URL env 
https://docs.mongodb.org/v3.0/reference/connection-string/

My apps are no longer working had to revert.

Thanks 
Bob

**Comment by josegonzalez** [comment]
This isn't the same as any other mongodb plugin, so I'm not quite sure what you mean by "reverting".

I can definitely fix the scheme though, that was an oversight. I don't use mongo ;)
