### ISSUE TITLE
Set a custom MONGO_URL for mongodump/restore

### ISSUE THREAD

**Issue by rjbernaldo** [dokku/dokku-mongo#101]
Is there a way to set a custom MONGO_URL so I can schedule this plugin to perform scheduled `mongodump`s from mongodb cloud atlas to s3?

**Comment by josegonzalez** [comment]
No, and I will not accept a pull request for that sort of functionality, as it sounds like what you actually want is a nicer CLI interface for mongodb in general.

**Comment by rjbernaldo** [comment]
No worries. Appreciate the quick response.
