### ISSUE TITLE
Scheduled backup leaves hanging containers: dokkupaas/s3backup

### ISSUE THREAD

**Issue by jcutrono** [dokku/dokku-mongo#104]
I have been using scheduled backups for a few weeks now. It seems that every so often, a container is left in an exited state. I am backing up every 2 hours and you can see that each run leaves an exited container. Any chance on each run to just kill all exited containers with this naming image name: dokkupaas/s3backup? [docker rmi $(docker images |grep 'dokkupaas/s3backup:0.8.0')]

![capture](https://user-images.githubusercontent.com/2238260/40700315-06571a0c-63a7-11e8-8b7a-3bfac8f2c30e.png)

**Comment by josegonzalez** [comment]
Looks like we might be missing `--rm` on the following `docker run` call:

https://github.com/dokku/dokku-mongo/blob/7867e9baeec6a58b87b24c200c68f4e2ac774a78/common-functions#L170

Can you try adding it to yours and seeing if it works? If so, I can update our code and make a new release (you'd have to revert the change locally for the `plugin:update` to work).

**Comment by josegonzalez** [comment]
Closed by https://github.com/dokku/dokku-mongo/commit/0619249d2ce22afe83e46ef937bd4d2e9d48a035

I derped the commit message 🤦‍♂️
