### ISSUE TITLE
Proper multiple apps linking

### ISSUE THREAD

**Issue by AlexBlokh** [dokku/dokku-mongo#107]
As I assume, there are no possible ways to connect multiple `apps` to a single `mongo docker instance` and provide them different `dbs`

f.e.
- I have `app1`, `app2`
- I spin `mongo1`
- link `mongo1` to `app1`, get mongo url with database name `app1` 
- and when I link `mongo1` to `app2` it gives me the same mongo uri with `app1` db name

is there any way multiple applications can use single mongo docker instance and have different dbs??

Regards

**Comment by josegonzalez** [comment]
Unfortunately, that is not currently possible. See [this issue](https://github.com/dokku/dokku-redis/issues/64) for work towards this.
