### ISSUE TITLE
Mongo 4.0.3

### ISSUE THREAD

**Issue by HmFlashy** [dokku/dokku-mongo#111]
Hello,
Have you planned to upgrade your plugin to accept the 4.0.3 version of mongodb?

Thank you,
Regards,
Hugo Maitre

**Comment by josegonzalez** [comment]
No we haven't, but pull requests are welcome!

**Comment by HmFlashy** [comment]
Pull request done and passing

**Comment by HmFlashy** [comment]
It will be useful to people that don't have acces to variable environments of the dokku host.
