### ISSUE TITLE
Log files grow very large

### ISSUE THREAD

**Issue by harrisreynolds** [dokku/dokku-mongo#114]
I recently has an issue where disk space filled up on my server.

Using the ncdu linux utility I was able to find an 83GB json file inside of the MongoDB docker container (build with dokku-mongo).

Ideally we could either turn off logging or have it roll when it hit a certain size or age.

**Comment by SeunghunSunmoonLee** [comment]
It happened to me. 
I ran `-type f -size +100000k -exec ls` to find out 
```
root@seunghunlee:~# find / -type f -size +100000k -exec ls -lh {} \;
-rw-rw---- 1 root utmp 113M Jan  1 06:24 /var/log/btmp.1
-rw-r--r-- 1 999 docker 100M Feb 18  2019 /var/lib/dokku/services/mongo/seunghunlee/data/journal/WiredTigerPreplog.0000000002
-rw-r--r-- 1 999 docker 100M Feb 18  2019 /var/lib/dokku/services/mongo/seunghunlee/data/journal/WiredTigerPreplog.0000000001
-rw-r--r-- 1 999 docker 100M Nov 16 13:16 /var/lib/dokku/services/mongo/meet/data/journal/WiredTigerPreplog.0000000002
-rw-r--r-- 1 999 docker 100M Nov 16 13:18 /var/lib/dokku/services/mongo/meet/data/journal/WiredTigerLog.0000000001
-rw-r--r-- 1 999 docker 100M Nov 16 13:16 /var/lib/dokku/services/mongo/meet/data/journal/WiredTigerPreplog.0000000001
```

**Comment by josegonzalez** [comment]
Those files are used by mongodb internally and probably shouldn't be deleted. Answer [here](https://stackoverflow.com/a/19535463/1515875) on why.

I'd be curious about that 83GB json file but I'm going to guess it's just mongodb.

You can modify your mongodb config at the path shown by `dokku mongo:info $SERVICE --config-dir` to combat this, but it's a bit beyond this plugin to do so without potentially having adverse effects on the running of mongodb. I'd refer to any documentation here.

Feel free to open a new ticket if there is more information or if you are having a similar issue and think Dokku should handle it (and have an idea as to how).
