### ISSUE TITLE
How do I update to latest mongo?

### ISSUE THREAD

**Issue by BigWillie** [dokku/dokku-mongo#116]
Installed this plugin last night. How do I update each database to mongo-db 4? Thanks

**Comment by devniel** [comment]
According to the docs, I think that you need to specify it via env variables, I think that dokku will search it on docker hub :

```
# you can also specify the image and image
# version to use for the service
# it *must* be compatible with the
# official mongo image
export MONGO_IMAGE="mongo"
export MONGO_IMAGE_VERSION="3.0.5"
dokku mongo:create lolipop
```

**Comment by josegonzalez** [comment]
You may also wish to look at the output of:

```
dokku mongo:help create
```

Which should show you options for installing with flags.

**Comment by jc-camosun** [comment]
How do you do this in a CI file?
For example, in my GitLab CI file I have:
`- ssh dokku@$DEPLOY_SRV config:set --global MONGO_IMAGE_VERSION="4.2.3"`
But it doesn't work.

**Comment by josegonzalez** [comment]
@jc-camosun did you check out the output of `dokku mongo:help create`?

**Comment by jc-camosun** [comment]
My apologies @josegonzalez. I somehow missed the flags. `-I` does indeed work.

**Comment by josegonzalez** [comment]
Glad that works :)
