### ISSUE TITLE
How to change environment variable name

### ISSUE THREAD

**Issue by imkrunal** [dokku/dokku-mongo#126]
so when we create and link database using it creates the environment variable with name `MONGO_URL` but I want to change that to be `DATABASE_URL`.
```
dokku mongo:create lolipop
dokku mongo:link lolipop playground
```
There should be an option to pass something like --as DATABASE to change it. Or is there any way to change it and not mentioned in docs?

**Comment by josegonzalez** [comment]
You can specify an alias via `--alias` when linking. [Here](https://github.com/dokku/dokku-mongo/blob/f494f1edbba3f1dc2c30653250e7e4f28677d54a/tests/service_link.bats#L113) is an example from our tests.
