### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by Flink** [dokku/dokku-mongo#13]
This plugin should be considered as ready for a 1.0 release.

**Comment by duller999** [comment]
I think the hook is wrong shouldn't it be docker-args-deploy

**Comment by josegonzalez** [comment]
Heh probably. @Flink mind updating that to be symlinks for all three docker-args phases in each plugin?

**Comment by Flink** [comment]
@josegonzalez will do ;)

**Comment by Flink** [comment]
Done for all services!
