### ISSUE TITLE
Expose all databases?

### ISSUE THREAD

**Issue by DenisNP** [dokku/dokku-mongo#130]
Hello there.

I have about 20 dokku apps and I want to periodically connect to each of it's databases. But I cannot `expose` all those 20 databases to just 4 different ports. How can I solve this? Should I `expose` each time I want to connect to the specific database and `unexpose` after that?

Thanks.

**Comment by josegonzalez** [comment]
You can either expose/unexpose, choose ports yourself, or let dokku choose random ports to expose on.
