### ISSUE TITLE
Changes to the MONGO_CONFIG_OPTIONS  config file shouldn't required a container rebuilt

### ISSUE THREAD

**Issue by iplanwebsites** [dokku/dokku-mongo#131]
The container needs to be rebuilt after changing the files. A simple restart doesn't do it.

**Comment by josegonzalez** [comment]
The `MONGO_CONFIG_OPTIONS` are passed as arguments to the container, so we will definitely need a new one. There isn't currently a way to check if the options are the same each time, so maybe we should respect a `--rm` flag and document how to change the options?

**Comment by iplanwebsites** [comment]
Good idea. It took me a while to discover MONGO_CONFIG_OPTIONS. A command to view/set those flags could be hand, it could print appropriate warnings to reboot the container on edits. Otherwise simple clarifications on how MONGO_CONFIG_OPTIONS works would be helpful.

**Comment by josegonzalez** [comment]
I keep thinking I should add a `:set` command to allow us to set multiple properties (including backup ones) for the plugin. In that way, `MONGO_CONFIG_OPTIONS` would be exposed as a service property, probably `container-arguments` or something. Same with env. Thoughts?
