### ISSUE TITLE
Dokku-Mongo uses deprecated `mongo` instead of `mongosh`

### ISSUE THREAD

**Issue by TimHal** [dokku/dokku-mongo#156]
## Description of problem
The plugin appears to use `mongo` which is deprecated in favor of the newer `mongosh`.

### How reproducible
Install the plugin.
Connect as admin via
`dokku mongo:connect-admin <service>`

### Steps to Reproduce

1. Install the plugin
2. `dokku mongo:connect-admin <service>`

#### Actual Results
A `mongo`-based connection with the warning

> ================
>Warning: the "mongo" shell has been superseded by "mongosh",
>which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
>an upcoming release.
>For installation instructions, see
>https://docs.mongodb.com/mongodb-shell/install/
>================

#### Expected Results
A `mongosh`-based connection

### `dokku report APP_NAME` output
No app required

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Following the dokku _getting started_ guide

**Comment by josegonzalez** [comment]
Is the mongo shell built into the official image?

**Comment by TimHal** [comment]
Yes, `mongo` is still kept for backwards compatibility I think but anything from version 5.x+ can use `mongosh`
