### ISSUE TITLE
mongodb plugin upgrade 

### ISSUE THREAD

**Issue by cburkins** [dokku/dokku-mongo#158]
Thank-you for dokku, very much enjoy using it.

Trying to understand how mongodb plugin gets upgraded.  Not the plugin itself, but the mongodb container.  Having only recently installed plugin, I'm on v5.0.9 of mongodb.

- How can I query if new MongoDB versions are available ?   Perhaps a dry-run flag ?
- How is the MongoDB container version chosen ?  e.g. I appear to be running v5.0.9, but v5.0.12 is available
- Does MongoDB get auto-upgraded periodically, or is that my responsibility to trigger manually ?

I tried the upgrade command, but seems to confirm that I'm on the "latest" version

<img width="787" alt="image" src="https://user-images.githubusercontent.com/9342308/189532230-560518a4-50b0-4959-be27-4d55f21d610a.png">

**Comment by cburkins** [comment]
Any ideas on this one ?   I'm hoping to proactively understand how mongo:upgrade works (and decides on mongo version).

**Comment by josegonzalez** [comment]
The image is set via an env var (in the config file, but overridable). IIRC there are flags for the upgrade command that let you change the image and image version (tag) used to run your database.

We periodically update the image in the plug-in as long as tests pass.

**Comment by cburkins** [comment]
@josegonzalez Thanks for the reply.   So if I want to (which I don't) hardcode the version of the mongoDB container that I'm using, where would I do that ?   And what events would cause dokku to attempt to upgrade the mongoDB container to the "current" (designated ?) version ?

**Comment by josegonzalez** [comment]
The container version we use to spawn your container (if it gets destroyed) is stored on disk during service creation iirc. We don't upgrade your version automatically otherwise, even if the version we specify with the plug-in changes.

**Comment by josegonzalez** [comment]
One note for anyone looking to get upgrade notifications - it's worth subscribing to an RSS feed or similar for your datastores and operating systems. This will allow you to better schedule upgrades since you'll at least be notified they exist. Most datastores have a feed, and many chat services (such as slack) have ways to subscribe to them :)
