### ISSUE TITLE
Replica Set needed

### ISSUE THREAD

**Issue by kamzata** [dokku/dokku-mongo#190]
I wrote a simple todo app using NextJS and I used MongoDB and Prisma as ORM.

The issue is Prisma complains MongoDB needs to be configured as Replica Set [as written here](https://www.prisma.io/docs/concepts/database-connectors/mongodb).

How can I configure MongoDB plugin in order to make it works?

I already [checked this](https://github.com/dokku/dokku-mongo/issues/88) but it didn't work. 

[Locally I successfully done this](https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/) and it worked.

**Comment by josegonzalez** [comment]
This isn't a feature supported out of the box by this plugin. Others may have gotten it working, but it's not something I planned on supporting. If [you'd like to sponsor this feature](https://github.com/dokku/.github/blob/master/SPONSORING.md), please let me know.

**Comment by kamzata** [comment]
> This isn't a feature supported out of the box by this plugin. Others may have gotten it working, but it's not something I planned on supporting. If [you'd like to sponsor this feature](https://github.com/dokku/.github/blob/master/SPONSORING.md), please let me know.

Thanks, I will sponsor for sure. I just don't understand the usefulness of this plugin without this (I think) basic feature. Is there a way to use it with Prisma or Mongoose without Replica Set? How?

**Comment by kamzata** [comment]
However, I think I successfully converted mongod Standalone to a Replica Set but my app still not work.

I took this steps:
- edited config options: `sudo nano /var/lib/dokku/services/mongo/$YOUR_SERVICE/CONFIG_OPTIONS`
- change its content to this `--keyFile /data/db/keyfile --replSet rs0 --storageEngine wiredTiger --auth`
- created a key file: `openssl rand -base64 756 > keyfile`
- then: `chmod 400 keyfile`
- then: `mv keyfile /var/lib/dokku/services/mongo/$YOUR_SERVICE/data/`
- then removed the container: `sudo docker rm -f dokku.mongo.$YOUR_SERVICE`
- then started again: `dokku mongo:start $YOUR_SERVICE`
- then connected to the mongodb instance: `dokku mongo:connect-admin $YOUR_SERVICE`
- then this:
```
use admin
rs.initiate()
use local
db.system.replset.find()
exit
```
- then: `dokku mongodb:restart $YOUR_SERVICE`
- connected again to the instance: `dokku mongo:connect-admin $YOUR_SERVICE`
- and check if it's running as Replica Set: `rs.status()`

As I said, now it seems to run as Replica Set but the app still doesn't work.

I checked the logs running:
```
dokku  mongo:logs $YOUR_SERVICE -t
```

but there's no output whenever I try to communicate from the app in order to read or write on the db.

I tried to reboot everything and unlink and link again the mongodb service to the app but without success.

**Comment by josegonzalez** [comment]
> I just don't understand the usefulness of this plugin without this (I think) basic feature

MongoDB Replica sets are _usually_ used for high availability and clustering, two things that _aren't_ goals for these plugins (no one has sponsored or contributed this sort of functionality in the 8 years this plugin has been around). I don't know why it doesn't work with Prisma either - we've had other users that have used Prisma just fine.

I'll keep this ticket open but I will say I don't have free personal time to spend on this so I likely won't be working on this. If others figure out how to get it running, I'd be more than happy to take a pull request (for docs or functionality).

**Comment by kamzata** [comment]
> > I just don't understand the usefulness of this plugin without this (I think) basic feature
> 
> MongoDB Replica sets are _usually_ used for high availability and clustering, two things that _aren't_ goals for these plugins (no one has sponsored or contributed this sort of functionality in the 8 years this plugin has been around). I don't know why it doesn't work with Prisma either - we've had other users that have used Prisma just fine.
> 
> I'll keep this ticket open but I will say I don't have free personal time to spend on this so I likely won't be working on this. If others figure out how to get it running, I'd be more than happy to take a pull request (for docs or functionality).

It needs Replica Sets [because of it supports nested writes and transactions require a replica set deployment](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb-typescript-mongodb#prerequisites).

**Comment by kamzata** [comment]
I eventually made it works. There were some entries in the collection formatted wrong. After clean the collection (`db.$collection.deleteMany({})`) it worked straight away. So, as far as I can see, the above procedure to convert MongoDB Standalone to a Replica Set is correct. Thanks.
