### ISSUE TITLE
Installation on 0.4.0

### ISSUE THREAD

**Issue by Xiangshen-Meng** [dokku/dokku-mongo#20]
Since dokku plugins-install is not available on 0.4.0, the installation may change to 

```
dokku plugin:install https://github.com/dokku/dokku-mongo.git
```

**Comment by josegonzalez** [comment]
Fixed by https://github.com/dokku/dokku-mongo/commit/5bd4f4f708a08e48025d4e6fd873e753389feab2, thanks for reporting!
