### ISSUE TITLE
< 3.0 images not loading. 

### ISSUE THREAD

**Issue by crm114** [dokku/dokku-mongo#25]
If I try to load 2.6.11 or 2.6.10 MongoDB images the create action hangs at "Waiting for container to be ready".

**Comment by Flink** [comment]
`docker logs` output is the following:
> Error parsing command line: unknown option storageEngine
> try 'mongod --help' for more information

So I think this option is only available on mongo 3+ :/ Will have a look about what we can do here.

**Comment by josegonzalez** [comment]
What did I set the storage engine to? If it's wildtiger, maybe we can just make that optional/configurable?

**Comment by Flink** [comment]
Yep it’s WiredTiger so we could check for mongo version and active it only when version > 3.0?

**Comment by josegonzalez** [comment]
I don't think we can just check for version, as it's possible to use `LATEST`.
