### ISSUE TITLE
Following "dokku mongo:link lolipop playground" doesn't expose env variables

### ISSUE THREAD

**Issue by mamalat** [dokku/dokku-mongo#27]
It only creates LINKS file, and I see that there is no code for exposing env variables.
When that planned to be added?.. or should I make a PR?

**Comment by Flink** [comment]
It will be added soon, already done on postgres, mariadb, mysql :)

**Comment by Flink** [comment]
(and actually env var are already exposed via the `docker-args-*` hooks but it doesn’t use `dokku config` at the moment)

**Comment by mamalat** [comment]
Got it, thank you. Works like a charm!

**Comment by josegonzalez** [comment]
I merged @Flink's pr, so this should be considered complete for the mongo plugin :)
