### ISSUE TITLE
Ability to --drop DB and do a full import

### ISSUE THREAD

**Issue by newbreedofgeek** [dokku/dokku-mongo#32]
Hello,

Not sure if this is an issue or just not documented.

I need to be able to do something like this:
dokku mongo:import current-db < new-db.tar --drop

i.e.
I'd like to import new-db.tar and drop current-db before the import happens.

Currently when I do:
dokku mongo:import current-db < new-db.tar

The DBs are "merged" which is not what you want in certain occasions.

In MongoDB world you can do this via, which is ideally what I'm after:
mongorestore --db current-db --drop new-db.tar

Thanks,
Mark.

**Comment by josegonzalez** [comment]
Can you just use the mongocli to drop the database manually and then run the import?

**Comment by josegonzalez** [comment]
@newbreedofgeek *bump*

**Comment by josegonzalez** [comment]
Closing as there hasn't been any response.
