### ISSUE TITLE
Unable to list Mongo services due to a `*` folder

### ISSUE THREAD

**Issue by ignlg** [dokku/dokku-mongo#40]
Same issue as https://github.com/dokku/dokku-mariadb/issues/30

    $ cd /var/lib/dokku/services/mongo
    $ ls -l
    total 4
    drwxr-xr-x 2 dokku dokku 4096 Nov  4 16:57 *

I just installed the plugin. No mongo service was created or linked yet.

**Comment by josegonzalez** [comment]
Okay now we are getting somewhere.

@Flink maybe somewhere `PLUGIN_DATA_ROOT` is adding a `*` and the `install` hook is creating that dir?

Also @Flink can you email me your shirt size/location :D

**Comment by Flink** [comment]
Ok I’ll try to reproduce and investigate :)

@josegonzalez No problem, will do!

**Comment by Flink** [comment]
I’m trying to reproduce in the dokku vagrant VM but no luck so far.
@ignlg How did you install the plugin? Do you have a `PLUGIN_DATA_ROOT` or `MONGO_ROOT` env var exported?

**Comment by ignlg** [comment]
I installed it with `dokku plugin:install https://github.com/dokku/dokku-mongo.git mongo` as `root` user. No var exported.

**Comment by Flink** [comment]
@ignlg do you have other non-core plugins installed?

**Comment by ignlg** [comment]
@Flink Yes, this is the plugins complete list:
```
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  builders             0.3.3 enabled    To run tools and package managers on build/release
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logging-supervisord  0.1.0 disabled   A plugin for dokku that injects supervisord
  logs                 0.4.0 enabled    dokku core logs plugin
  mariadb              1.0.0 enabled    dokku mariadb service plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.4.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  redirect             0.4.0 enabled    Simple redirects for apps
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
  volume               1.0.0 enabled    persistent storage plugin for dokku
```

**Comment by ignlg** [comment]
I just detected that it's created again from time to time. I don't have the steps to reproduce it but I'll try to monitor that folder on every command to isolate them.

(In fact I saw this behaviour on `mariadb` but as it seems the same issue as dokku/dokku-mariadb#30 and you're assigned to both, I'll use this issue as an unified feedback. @Flink, is it right for you?)

**Comment by Flink** [comment]
@ignlg yeah no problem for the feedback on this issue :)
