### ISSUE TITLE
mongo:link infinite loop

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku-mongo#44]
I have an app that was working fine, but suddenly when trying to link a new database, the  command mongo:link crashed, is an infinite loop. How to fix it?

**Comment by internetstyle** [comment]
Symptoms:

Trying: dokku mongo:link databasename appname
Results: infinite loop.

Trying: dokku mongo:destroy databasename
Results: Cannot delete linked service

Trying: dokku mongo:unlink databasename appname
Results:  Not linked to app appname

**Comment by josegonzalez** [comment]
Can you run those commands with `dokku trace on`?

**Comment by internetstyle** [comment]
Follows the output of the three commands. Thanks.

https://gist.github.com/internetstyle/3d54ada58b01d8c5131a

**Comment by josegonzalez** [comment]
Seems like you hit a limit on the number of databases that can be linked to a given service using our built-in aliasing. Definitely still an issue. The workaround would be to manually define an alias, though that isn't currently possible.

I'm going to close this in favor of tracking the work here: https://github.com/dokku/dokku-redis/issues/52#issuecomment-243019725

**Comment by josegonzalez** [comment]
See dokku/dokku-redis/issues/64 for more information.
