### ISSUE TITLE
How to attach a persistent volume?

### ISSUE THREAD

**Issue by derekstavis** [dokku/dokku-mongo#55]
I'm trying to use `dokku docker-options` to add a persistent volume to mongodb container. Unfortunately, I found no way of doing it because `docker-options` expect and app name and theoretically this plugin doesn't expose an app. 

What's the right way of accomplishing this task?

**Comment by josegonzalez** [comment]
A persistent volume? The mongodb container already persists it's data to disk, you don't need to do anything.

**Comment by derekstavis** [comment]
At [this line](https://github.com/dokku/dokku-mongo/blob/master/commands#L47) the persistent volume is mounted inside mongo's docker container. I'd like to have a way to specify my own path, instead of needing to use the default `$SERVICE_ROOT/data` directory.

**Comment by josegonzalez** [comment]
Sorry, that's not possible, and I don't see any benefits to being able to do this.

**Comment by derekstavis** [comment]
Yes. In my scenario I have some external attached disks in my cloud instance, and the volumes are mounted in `/mnt/db-dev` and `/mnt/db-prod`, for example. I could mount inside `dokku-mongo`, but this doesn't look good to me.

**Comment by josegonzalez** [comment]
Try a symlink instead?

**Comment by derekstavis** [comment]
Thanks for the fast response. I have opted to mount the volume inside plugin's default directory.
