### ISSUE TITLE
dokku nodejs and mongo issue

### ISSUE THREAD

**Issue by parser22** [dokku/dokku-mongo#68]
my nodejs instance can not connect to the mongo service, failing with 

```
error: Uncaught internal server error. { [MongoError: getaddrinfo ENOTFOUND dokku-mongo-testdb dokku-mongo-testdb:27017]
  name: 'MongoError',
  message: 'getaddrinfo ENOTFOUND dokku-mongo-tapitoodb dokku-mongo-testdb:27017' } Error: getaddrinfo ENOTFOUND dokku-mongo-tapitoodb dokku-mongo-testdb:27017
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

**Comment by josegonzalez** [comment]
Is this a dokku app that is attempting to connect to your container, and did you link the service to your application?

**Comment by sheldonnbbaker** [comment]
@parser22 Did you figure this one out? I'm having the same issue.

**Comment by josegonzalez** [comment]
@sheldonnbbaker I'm assuming you linked the two services and then performed a `ps:rebuild` of your application for good measure? If not, I can probably help you out on slack/irc (I am `savant` on both).
