### ISSUE TITLE
use --gzip --archive options with export import

### ISSUE THREAD

**Issue by paulwalker** [dokku/dokku-mongo#70]
My bash skills aren't superior, but I was able to use this command in my dokku environment

```
sudo docker exec -it {container_name} mongodump -d {name} -u {name} -p {password} --gzip --archive > {name}.archive
```

faster, smaller file and doesn't output the full archive to the terminal. Can we enhance the export and import commands to support this instead of the tar thing it's doing right now?

**Comment by paulwalker** [comment]
for reference: https://www.mongodb.com/blog/post/archiving-and-compression-in-mongodb-tools

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by paulwalker** [comment]
Like I said, my bash skills aren't great. Apparently the above command I gave does not work as it copied the complete output to the file, not just the contents of the archive. The --quiet option did not help. Outputting to a local file first did work however. 
```
docker exec -it {container_name} mongodump -d {name} -u {name} -p {password} --gzip --archive={name}.archive
docker cp {container_name}:/{name}.archive .
```
Still trying to figure out how to get the above to work with one command

**Comment by kimus** [comment]
I found out that the mongo:export doesn't export in gzip format.
I guess you just need to change from -o $DIR and the tar and rm DIR to --gzip --archive=- and that's it.
Is there a need for a pull request?

**Comment by josegonzalez** [comment]
I don't know, is there? I don't use mongodb - frankly I don't see why anyone does, there are better datastores out there for what it does - so I defer to the actual users of the service.

**Comment by josegonzalez** [comment]
Closed by #93.

**Comment by malixsys** [comment]
Any idea how to use with `--noIndexRestore` ?

**Comment by josegonzalez** [comment]
@malixsys please open a new issue, but also we don't support that flag at this time.

**Comment by malixsys** [comment]
Ok, no need, I managed with:
`mongorestore --noIndexRestore --host YOUR_HOST --db YOUR_DB --port YOUR_PORT --username USER --password PW --gzip --archive=dump-previously.tar`
