### ISSUE TITLE
mongo:connect-admin not working

### ISSUE THREAD

**Issue by tofuness** [dokku/dokku-mongo#73]
Currently using `dokku 0.6.5` and latest version of `dokku-mongo`.

When I run `dokku mongo:connect-admin xyz` I get:

```
/var/lib/dokku/plugins/enabled/mongo/commands: line 23: 
/var/lib/dokku/plugins/enabled/mongo/subcommands/connect-admin: Permission denied
```

Let me know if I can help in any way. Thank you!

**Comment by josegonzalez** [comment]
What is that file owned by?

**Comment by tofuness** [comment]
Found this:
![image](https://cloud.githubusercontent.com/assets/2232877/17083302/d2517974-519b-11e6-8766-820eb3e03237.png)

So I tried doing `chmod 755 connect-admin` and now when I run `dokku mongo:connect-admin xyz` I get this error: `MongoDB service mongo:connect-admin does not exist`.

**Comment by josegonzalez** [comment]
I fixed the command permissions, a bug in the code itself, and added tests. If you update, you should be able to use that command just fine now.

**Comment by tofuness** [comment]
Great work, @josegonzalez .
