### ISSUE TITLE
Question: Memory Limit

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku-mongo#80]
How can I limit memory usage by a mongo container? Thanks.

**Comment by josegonzalez** [comment]
It's not currently possible to do this.

**Comment by tucnak** [comment]
@josegonzalez It'd be cool though.

**Comment by josegonzalez** [comment]
@tucnak would maybe be, can you work on a pull request for this change?

**Comment by tucnak** [comment]
I'd be happy to, actually! I'm rather new in the dockerland but I already feel quite excited, if only you could help me with some clues along the way.
