### ISSUE TITLE
Error on backup

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku-mongo#81]
When I run backup getting this error:

dokku mongo:backup-auth testexyzz-db "xxx" "yyy"
dokku mongo:backup testexyzz-db testexyzz

gof3r error: Post https://testexyzz.s3-us-east-1x-amz-request-id.amazonaws.com/mongo-testexyzz-db-2017-04-17-21-23-22.tgz?uploads=: dial tcp: lookup testexyzz.s3-us-east-1x-amz-request-id.amazonaws.com on 72.14.179.5:53: no such host

Credentials added, and bucket existing. Someone can help me. Thanks.

**Comment by josegonzalez** [comment]
Upgrade your plugin, you are not running latest, which fixes the issue.

**Comment by internetstyle** [comment]
I do it only running "dokku plugin:update mongo" or is needed stop all containers? Thank you.

**Comment by josegonzalez** [comment]
You can just run that command and it'll update the mongo plugin just fine. It won't restart any running containers.
