### ISSUE TITLE
how to export / import a specific collection

### ISSUE THREAD

**Issue by templth** [dokku/dokku-mongo#83]
Hello,

Is there a way to import / export a specific collection through dokku-mongo?

Thanks very much for your help!
Thierry

**Comment by josegonzalez** [comment]
No there is not a way to do that natively. You may be able to shim something using the `connect` functionality, but the import/export functionality is aimed at backup usage, which typically entails an entire datastore, not just a subset.

**Comment by templth** [comment]
@josegonzalez Thanks very much for your (very) quick answer!
