### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by kruyvanna** [dokku/dokku-mongo#87]
Hi, when I do:

`dokku mongo:link mongo att.pmapp.work `

I get 

`/var/lib/dokku/plugins/available/docker-options/functions: line 89: /home/dokku/att.pmapp.work/DOCKER_OPTIONS_DEPLOY: Permission denied`

**Comment by josegonzalez** [comment]
What is the output of:

```
ls -lah /home/dokku/att.pmapp.work
```

**Comment by kruyvanna** [comment]
Hi @josegonzalez  sorry for late reply.
Here is the output

`total 84K
drwxrwxr-x  8 dokku dokku 4.0K Jul  7 10:12 .
drwxr-xr-x  6 dokku dokku 4.0K Jul  7 08:35 ..
drwxrwxr-x  2 dokku dokku 4.0K Jul  7 08:17 branches
drwxrwxr-x  3 32767 32767 4.0K Jul  7 10:11 cache
-rw-rw-r--  1 dokku dokku   66 Jul  7 08:17 config
-rw-rw-r--  1 dokku dokku   65 Jul  7 10:12 CONTAINER.web.1
-rw-rw-r--  1 dokku dokku   73 Jul  7 08:17 description
-rw-r--r--  1 dokku dokku   43 Jul  7 09:08 DOCKER_OPTIONS_BUILD
-rw-r--r--  1 root  root    24 Jul  7 08:34 DOCKER_OPTIONS_DEPLOY
-rw-rw-r--  1 dokku dokku    6 Jul  7 08:20 DOKKU_SCALE
-rw-------  1 dokku dokku  135 Jul  7 09:23 ENV
-rw-rw-r--  1 dokku dokku   23 Jul  7 08:17 HEAD
drwxrwxr-x  2 dokku dokku 4.0K Jul  7 08:17 hooks
drwxrwxr-x  2 dokku dokku 4.0K Jul  7 08:17 info
-rw-rw-r--  1 dokku dokku   11 Jul  7 10:12 IP.web.1
-rw-------  1 dokku dokku 1.1K Jul  7 10:12 nginx.conf
drwxrwxr-x 35 dokku dokku 4.0K Jul  7 10:10 objects
-rw-rw-r--  1 dokku dokku    5 Jul  7 10:12 PORT.web.1
drwxrwxr-x  4 dokku dokku 4.0K Jul  7 08:17 refs
-rw-rw-r--  1 dokku dokku  104 Jul  7 10:12 URLS
-rw-rw-r--  1 dokku dokku   15 Jul  7 09:23 VHOST`

**Comment by josegonzalez** [comment]
```
chown dokku:dokku /home/dokku/att.pmapp.work/DOCKER_OPTIONS_DEPLOY
```

**Comment by kruyvanna** [comment]
thanks @josegonzalez 
Works like magic!
