### ISSUE TITLE
Backups cannot be imported

### ISSUE THREAD

**Issue by jlcastillo** [dokku/dokku-mongo#95]
There are several problems:

1) Backups have a TGZ format, but mongo:import only supports TAR.
2) The structure of folders and collections inside the TGZ are wrong, and mongo:import doesn't understand them.

**Comment by josegonzalez** [comment]
What backups are you talking about? The `import` subcommands for service plugins are meant to be used in conjunction with the respective `export` subcommands. In this case, the format we use for exports [is not tgz](https://github.com/dokku/dokku-mongo/blob/master/functions#L102) unless I am mistaken.

**Comment by jlcastillo** [comment]
I'm talking about the backups that you make with mongo:backup. Those cannot be imported with:

`dokku mongo:import service < backup_file`

they instead need to be imported with something like:

`tar zxf backup_file &&  `dokku mongo:import service < backup_file/export`

it would make sense to backup with the same format of `mongo:export`, or at least document how to restore backups.

**Comment by josegonzalez** [comment]
Yeah I think the documentation route is the way to go here as - iirc - the backups also include configuration files etc., which may not make too much sense to "import".

**Comment by josegonzalez** [comment]
This issue was moved to dokku/dokku-redis#100
