### ISSUE TITLE
IAM auth doesn't work for backups

### ISSUE THREAD

**Issue by jlcastillo** [dokku/dokku-mongo#96]
Problems:

1) the code in common-functions => service_backup()  is clearly wrong, it always throws an error message when you set the --use-iam option. It was apparently copy-pasted from the dokku postgres plugin.

2) the mongo:backup-auth should allow to store the --use-iam preferences, otherwise those cannot be passed to mongo:backup-schedule.

3) mongo:backup-schedule should write the --use-iam in CRON,  so that mongo:backup can receive it.

**Comment by josegonzalez** [comment]
Good catch. I'll see if I can somehow repro the bugs locally and fix - testing IAM backups is a pain as there isn't a super bulletproof way of doing it other than spinning up an AWS instance, which can be a bit costly.

**Comment by josegonzalez** [comment]
Closing in favor of the linked redis issue. I'm hoping I'll have some time this week to devote to fixing this issue - should be straightforward to fix _at least_ the `:backup` subcommand - but would appreciate any help in all cases :)
